apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: scraper-readonly
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scraper-readonly-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: scraper-irsa
    namespace: default
roleRef:
  kind: Role
  name: scraper-readonly
  apiGroup: rbac.authorization.k8s.io 