apiVersion: v1
kind: Secret
metadata:
  name: scraper-secrets
  namespace: default
stringData:
  DATABASE_URL: "postgresql://scraper:scraperpass@db:5432/scraperdb"
  CLARK_COUNTY_USERNAME: "testuser"
  CLARK_COUNTY_PASSWORD: "testpass"
# For production, use AWS Secrets Manager and IRSA to inject secrets securely. 