name: Test Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        id: pytest
        run: pytest scraper/tests/ || echo "pytest_failed=1" >> $GITHUB_ENV
      - name: Send SNS alert on failure
        if: env.pytest_failed == '1'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2
          SNS_ALERTS_TOPIC_ARN: ${{ secrets.SNS_ALERTS_TOPIC_ARN }}
        run: |
          aws sns publish --topic-arn "$SNS_ALERTS_TOPIC_ARN" --message "[ALERT] E2E tests failed in CI for ${{ github.repository }}@${{ github.sha }}. See run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" 